name: Maven Package on Push

on:
  push:
    branches:
      - "*" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Maven Wrapper
        run: |
          chmod +x mvnw
          ./mvnw --version

      - name: Build with Maven
        run: |
          ./mvnw clean package -B

      - name: Check if JAR was built
        run: |
          if [ ! -f "target/*.jar" ]; then
            echo "No JAR file found in target/ directory"
            exit 1
          else
            echo "JAR file built successfully"
            ls -la target/*.jar
          fi
